name: ci
on: [push]

jobs:
  create-dummy-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create dummy files
      - name: Create Dummy Files
        run: |
          touch dummy.aab
          touch keystore.jks
          ls -l dummy.aab keystore.jks  # Debug: confirm files exist
          echo "Created dummy.aab and keystore.jks"

      # Upload dummy files as artifacts
      - name: Upload Dummy Files
        uses: actions/upload-artifact@v3
        with:
          name: dummy-files
          path: |
            dummy.aab
            keystore.jks

  test-valid-inputs:
    runs-on: ubuntu-latest
    needs: create-dummy-files  
    steps:
      - uses: actions/checkout@v4

      - name: Download Dummy Files
        uses: actions/download-artifact@v3
        with:
          name: dummy-files

      - name: Run Bundletool Action (Valid Inputs)
        uses: ./
        with:
          bundletool-version: '1.18.1'
          java-version: '17'
          bundle-file: 'dummy.aab'
          output-file: 'app-release.apks'
          keystore-file: 'keystore.jks'
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          key-alias: ${{ secrets.KEY_ALIAS }}
          key-password: ${{ secrets.KEY_PASSWORD }}

      # Check output and set flag
      - name: Check Output
        id: check-output
        continue-on-error: true 
        run: |
          echo "Checking for app-release.apks..."
          ls -l .  # Debug: list directory contents
          if [ -f "app-release.apks" ]; then
            echo "Success: app-release.apks exists"
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Note: app-release.apks was not created (expected with dummy files)"
            echo "file_exists=false" >> $GITHUB_OUTPUT
          fi
          echo "file_exists output set to: ${{ steps.check-output.outputs.file_exists }}"

      # Debug: Log the condition result
      - name: Debug Condition
        run: |
          echo "File exists? ${{ steps.check-output.outputs.file_exists }}"
          if [ "${{ steps.check-output.outputs.file_exists }}" = "true" ]; then
            echo "Condition is true, upload should proceed"
          else
            echo "Condition is false, upload should be skipped"
          fi

      # Upload artifact only if it exists
      - name: Upload Artifact
        if: ${{ steps.check-output.outputs.file_exists == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: app-apks
          path: app-release.apks