name: ci
on: [push]

jobs:
  create-dummy-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create dummy files
      - name: Create Dummy Files
        run: |
          touch dummy.aab
          touch keystore.jks
          echo "Created dummy.aab and keystore.jks"

      # Upload dummy files as artifacts for inspection
      - name: Upload Dummy Files
        uses: actions/upload-artifact@v3
        with:
          name: dummy-files
          path: |
            dummy.aab
            keystore.jks

  test-valid-inputs:
    runs-on: ubuntu-latest
    needs: create-dummy-files  
    steps:
      - uses: actions/checkout@v4

      - name: Download Dummy Files
        uses: actions/download-artifact@v3
        with:
          name: dummy-files

      - name: Run Bundletool Action (Valid Inputs)
        uses: ./
        with:
          bundletool-version: '1.18.1'
          java-version: '17'
          bundle-file: 'dummy.aab'
          output-file: 'app-release.apks'
          keystore-file: 'keystore.jks'
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          key-alias: ${{ secrets.KEY_ALIAS }}
          key-password: ${{ secrets.KEY_PASSWORD }}

      - name: Check Output
        run: |
          if [ ! -f "app-release.apks" ]; then
            echo "Error: app-release.apks was not created"
            exit 1
          fi
          echo "Success: app-release.apks exists"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-apks
          path: app-release.apks